#!/bin/bash
# Pre-push hook for vite-plugin-tana
#
# Note: tana-edge version syncing was removed because package.json now uses
# "*" for optionalDependencies, which always pulls the latest version from npm.
# No more hardcoded versions = no more version drift issues!

exit 0
